version: "3.7"
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: round1fight
    ports:
      - "5439:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024MB"
    volumes:
      - /tmp/round1fight/pg/data:/var/lib/postgresql/data
