// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        string
	Nickname  string
	Name      string
	Birthday  string
	Stack     []string
	Docsearch interface{}
	Trigram   pgtype.Text
}
