// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: queries.sql

package repo

import (
	"context"
)

const getPerson = `-- name: GetPerson :one
SELECT id, nickname, name, stack FROM Person where id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id string) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Name,
		&i.Stack,
	)
	return i, err
}
